# Generated by Django 6.0.2 on 2026-02-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInquiry',
        ),
    ]
